actions

diff --git a/.github/workflows/non-prod-pipeline.yaml b/.github/workflows/non-prod-pipeline.yaml
--- a/.github/workflows/non-prod-pipeline.yaml
+++ b/.github/workflows/non-prod-pipeline.yaml
@@ -3,13 +3,18 @@ name: NON-PROD Pipeline
 on:
   workflow_call:
     inputs:
+      component:
+        required: true
+        type: string
+
       version:
         required: true
         type: string
+
       environment:
         required: true
         type: string
-        
+
 permissions:
   contents: read
   statuses: write
@@ -27,7 +32,6 @@ jobs:
 
           echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_ENV"
           echo "App version: $APP_VERSION"
-          
 
       - name: Check required commit statuses
         id: gate
@@ -77,25 +81,138 @@ jobs:
           aws-region: us-east-1
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
       - name: authenticate to EKS
         run: |
           aws eks update-kubeconfig --region us-east-1 --name roboshop-dev
           kubectl get nodes
 
       - name: checkout deploy repo
-        uses: actions/checkout@v6
+        uses: actions/checkout@v4
         with:
-         repository: rajasekharburri/${{ inputs.component }}-deploy
+          repository: rajasekharburri/${{ inputs.component }}-deploy
 
       - name: deploy to ${{ inputs.environment }} cluster
         id: uat_deploy
-        run: "helm upgrade --install catalogue -f values-dev.yaml -n roboshop --set deployment.imageVersion=${APP_VERSION} --atomic --wait --timeout=5m ."
+        run: |
+          helm upgrade --install catalogue \
+            -f values-dev.yaml \
+            -n roboshop \
+            --set deployment.imageVersion=${APP_VERSION} \
+            --atomic \
+            --wait \
+            --timeout=5m .
 
       - name: Update Deploy status
         if: always()
         uses: rajasekharburri-git-actions/workflows/.github/actions/update-commit-status@main
         with:
           sha: ${{ inputs.version }}
-          state: ${{ steps.uat_deploy.outcome }}     # success / failure / cancelled
+          state: ${{ steps.uat_deploy.outcome }}
           context: UAT_DEPLOY
           description: ${{ steps.uat_deploy.outcome }}
+
+
+
+
+# name: NON-PROD Pipeline
+
+# on:
+#   workflow_call:
+#     inputs:
+#       version:
+#         required: true
+#         type: string
+#       environment:
+#         required: true
+#         type: string
+        
+# permissions:
+#   contents: read
+#   statuses: write
+
+# jobs:
+#   non-prod-gate:
+#     runs-on: self-hosted
+
+#     steps:
+#       - name: Compute short commit
+#         id: commit
+#         run: |
+#           SHORT_SHA="${{ inputs.version }}"
+#           APP_VERSION="${SHORT_SHA:0:9}"
+
+#           echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_ENV"
+#           echo "App version: $APP_VERSION"
+          
+
+#       - name: Check required commit statuses
+#         id: gate
+#         shell: bash
+#         run: |
+#           echo "🔍 Checking commit statuses for ${{ inputs.version }}"
+
+#           REQUIRED_CONTEXTS=(
+#             "DEV_DEPLOY"
+#             "DOCKER_BUILD"
+#             "UNIT_TESTS"
+#             "SECURITY_CHECK"
+#           )
+
+#           RESPONSE=$(curl -s \
+#             -H "Authorization: Bearer ${{ github.token }}" \
+#             -H "Accept: application/vnd.github+json" \
+#             "https://api.github.com/repos/${{ github.repository }}/commits/${{ inputs.version }}/statuses")
+
+#           FAILED=0
+
+#           for CONTEXT in "${REQUIRED_CONTEXTS[@]}"; do
+#             STATE=$(echo "$RESPONSE" | jq -r \
+#               ".[] | select(.context == \"$CONTEXT\") | .state" | head -n 1)
+
+#             if [ -z "$STATE" ]; then
+#               echo "❌ $CONTEXT → status missing"
+#               FAILED=1
+#             elif [ "$STATE" != "success" ]; then
+#               echo "❌ $CONTEXT → $STATE"
+#               FAILED=1
+#             else
+#               echo "✅ $CONTEXT → success"
+#             fi
+#           done
+
+#           if [ "$FAILED" -eq 1 ]; then
+#             echo "🚫 UAT gate failed"
+#             exit 1
+#           fi
+
+#           echo "🎉 All required checks passed"
+
+#       - name: Configure AWS Credentials
+#         uses: aws-actions/configure-aws-credentials@v6.1.0
+#         with:
+#           aws-region: us-east-1
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#       - name: authenticate to EKS
+#         run: |
+#           aws eks update-kubeconfig --region us-east-1 --name roboshop-dev
+#           kubectl get nodes
+
+#       - name: checkout deploy repo
+#         uses: actions/checkout@v6
+#         with:
+#          repository: rajasekharburri/${{ inputs.component }}-deploy
+
+#       - name: deploy to ${{ inputs.environment }} cluster
+#         id: uat_deploy
+#         run: "helm upgrade --install catalogue -f values-dev.yaml -n roboshop --set deployment.imageVersion=${APP_VERSION} --atomic --wait --timeout=5m ."
+
+#       - name: Update Deploy status
+#         if: always()
+#         uses: rajasekharburri-git-actions/workflows/.github/actions/update-commit-status@main
+#         with:
+#           sha: ${{ inputs.version }}
+#           state: ${{ steps.uat_deploy.outcome }}     # success / failure / cancelled
+#           context: UAT_DEPLOY
+#           description: ${{ steps.uat_deploy.outcome }}
